const ang1 = "ੴ ਸਤਿ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਨਿਰਭਉ ਨਿਰਵੈਰੁ ਅਕਾਲ ਮੂਰਤਿ ਅਜੂਨੀ ਸੈਭੰ ਗੁਰ ਪ੍ਰਸਾਦਿ ॥॥ ਜਪੁ ॥ਆਦਿ ਸਚੁ ਜੁਗਾਦਿ ਸਚੁ ॥ ਹੈ ਭੀ ਸਚੁ ਨਾਨਕ ਹੋਸੀ ਭੀ ਸਚੁ ॥੧॥ਸੋਚੈ ਸੋਚਿ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥ ਚੁਪੈ ਚੁਪ ਨ ਹੋਵਈ ਜੇ ਲਾਇਰਹਾ ਲਿਵ ਤਾਰ ॥ ਭੁਖਿਆ ਭੁਖ ਨ ਉਤਰੀ ਜੇ ਬੰਨਾ ਪੁਰੀਆ ਭਾਰ ॥ ਸਹਸਸਿਆਣਪਾ ਲਖ ਹੋਹਿ ਤ ਇਕ ਨ ਚਲੈ ਨਾਲਿ ॥ ਕਿਵ ਸਚਿਆਰਾ ਹੋਈਐਕਿਵ ਕੂੜੈ ਤੁਟੈ ਪਾਲਿ ॥ ਹੁਕਮਿ ਰਜਾਈ ਚਲਣਾ ਨਾਨਕ ਲਿਖਿਆ ਨਾਲਿ॥੧॥ ਹੁਕਮੀ ਹੋਵਨਿ ਆਕਾਰ ਹੁਕਮੁ ਨ ਕਹਿਆ ਜਾਈ ॥ ਹੁਕਮੀ ਹੋਵਨਿਜੀਅ ਹੁਕਮਿ ਮਿਲੈ ਵਡਿਆਈ ॥ ਹੁਕਮੀ ਉਤਮੁ ਨੀਚੁ ਹੁਕਮਿ ਲਿਖਿ ਦੁਖਸੁਖ ਪਾਈਅਹਿ ॥ ਇਕਨਾ ਹੁਕਮੀ ਬਖਸੀਸ ਇਕਿ ਹੁਕਮੀ ਸਦਾਭਵਾਈਅਹਿ ॥ ਹੁਕਮੈ ਅੰਦਰਿ ਸਭੁ ਕੋ ਬਾਹਰਿ ਹੁਕਮ ਨ ਕੋਇ ॥ ਨਾਨਕਹੁਕਮੈ ਜੇ ਬੁਝੈ ਤ ਹਉਮੈ ਕਹੈ ਨ ਕੋਇ ॥੨॥ ਗਾਵੈ ਕੋ ਤਾਣੁ ਹੋਵੈ ਕਿਸੈ ਤਾਣੁ॥ ਗਾਵੈ ਕੋ ਦਾਤਿ ਜਾਣੈ ਨੀਸਾਣੁ ॥ ਗਾਵੈ ਕੋ ਗੁਣ ਵਡਿਆਈਆ ਚਾਰ ॥ਗਾਵੈ ਕੋ ਵਿਦਿਆ ਵਿਖਮੁ ਵੀਚਾਰੁ ॥ ਗਾਵੈ ਕੋ ਸਾਜਿ ਕਰੇ ਤਨੁ ਖੇਹ ॥ ਗਾਵੈਕੋ ਜੀਅ ਲੈ ਫਿਰਿ ਦੇਹ ॥";
const ang2 = "ਗਾਵੈਕੋ ਜਾਪੈ ਦਿਸੈ ਦੂਰਿ ॥ ਗਾਵੈ ਕੋ ਵੇਖੈ ਹਾਦਰਾ ਹਦੂਰਿ ॥ ਕਥਨਾ ਕਥੀ ਨ ਆਵੈ ਤੋਟਿ ॥ਕਥਿ ਕਥਿ ਕਥੀ ਕੋਟੀ ਕੋਟਿ ਕੋਟਿ ॥ ਦੇਦਾ ਦੇ ਲੈਦੇ ਥਕਿ ਪਾਹਿ ॥ ਜੁਗਾ ਜੁਗੰਤਰਿ ਖਾਹੀਖਾਹਿ ॥ ਹੁਕਮੀ ਹੁਕਮੁ ਚਲਾਏ ਰਾਹੁ ॥ ਨਾਨਕ ਵਿਗਸੈ ਵੇਪਰਵਾਹੁ ॥੩॥ ਸਾਚਾ ਸਾਹਿਬੁਸਾਚੁ ਨਾਇ ਭਾਖਿਆ ਭਾਉ ਅਪਾਰੁ ॥ ਆਖਹਿ ਮੰਗਹਿ ਦੇਹਿ ਦੇਹਿ ਦਾਤਿ ਕਰੇ ਦਾਤਾਰੁ ॥ਫੇਰਿ ਕਿ ਅਗੈ ਰਖੀਐ ਜਿਤੁ ਦਿਸੈ ਦਰਬਾਰੁ ॥ ਮੁਹੌ ਕਿ ਬੋਲਣੁ ਬੋਲੀਐ ਜਿਤੁ ਸੁਣਿ ਧਰੇਪਿਆਰੁ ॥ ਅੰਮ੍ਰਿਤ ਵੇਲਾ ਸਚੁ ਨਾਉ ਵਡਿਆਈ ਵੀਚਾਰੁ ॥ ਕਰਮੀ ਆਵੈ ਕਪੜਾ ਨਦਰੀਮੋਖੁ ਦੁਆਰੁ ॥ ਨਾਨਕ ਏਵੈ ਜਾਣੀਐ ਸਭੁ ਆਪੇ ਸਚਿਆਰੁ ॥੪॥ ਥਾਪਿਆ ਨ ਜਾਇਕੀਤਾ ਨ ਹੋਇ ॥ ਆਪੇ ਆਪਿ ਨਿਰੰਜਨੁ ਸੋਇ ॥ ਜਿਨਿ ਸੇਵਿਆ ਤਿਨਿ ਪਾਇਆ ਮਾਨੁ ॥ਨਾਨਕ ਗਾਵੀਐ ਗੁਣੀ ਨਿਧਾਨੁ ॥ ਗਾਵੀਐ ਸੁਣੀਐ ਮਨਿ ਰਖੀਐ ਭਾਉ ॥ ਦੁਖੁ ਪਰਹਰਿਸੁਖੁ ਘਰਿ ਲੈ ਜਾਇ ॥ ਗੁਰਮੁਖਿ ਨਾਦੰ ਗੁਰਮੁਖਿ ਵੇਦੰ ਗੁਰਮੁਖਿ ਰਹਿਆ ਸਮਾਈ ॥ ਗੁਰੁਈਸਰੁ ਗੁਰੁ ਗੋਰਖੁ ਬਰਮਾ ਗੁਰੁ ਪਾਰਬਤੀ ਮਾਈ ॥ ਜੇ ਹਉ ਜਾਣਾ ਆਖਾ ਨਾਹੀ ਕਹਣਾਕਥਨੁ ਨ ਜਾਈ ॥";
const ang = "ਗੁਰਾ ਇਕ ਦੇਹਿ ਬੁਝਾਈ ॥ ਸਭਨਾ ਜੀਆ ਕਾ ਇਕੁ ਦਾਤਾ ਸੋ ਮੈਵਿਸਰਿ ਨ ਜਾਈ ॥੫॥ ਤੀਰਥਿ ਨਾਵਾ ਜੇ ਤਿਸੁ ਭਾਵਾ ਵਿਣੁ ਭਾਣੇ ਕਿ ਨਾਇ ਕਰੀ ॥ਜੇਤੀ ਸਿਰਠਿ ਉਪਾਈ ਵੇਖਾ ਵਿਣੁ ਕਰਮਾ ਕਿ ਮਿਲੈ ਲਈ ॥ ਮਤਿ ਵਿਚਿ ਰਤਨ ਜਵਾਹਰਮਾਣਿਕ ਜੇ ਇਕ ਗੁਰ ਕੀ ਸਿਖ ਸੁਣੀ ॥ ਗੁਰਾ ਇਕ ਦੇਹਿ ਬੁਝਾਈ ॥ ਸਭਨਾ ਜੀਆ ਕਾਇਕੁ ਦਾਤਾ ਸੋ ਮੈ ਵਿਸਰਿ ਨ ਜਾਈ ॥੬॥ ਜੇ ਜੁਗ ਚਾਰੇ ਆਰਜਾ ਹੋਰ ਦਸੂਣੀ ਹੋਇ ॥ਨਵਾ ਖੰਡਾ ਵਿਚਿ ਜਾਣੀਐ ਨਾਲਿ ਚਲੈ ਸਭੁ ਕੋਇ ॥ ਚੰਗਾ ਨਾਉ ਰਖਾਇ ਕੈ ਜਸੁ ਕੀਰਤਿਜਗਿ ਲੇਇ ॥ ਜੇ ਤਿਸੁ ਨਦਰਿ ਨ ਆਵਈ ਤ ਵਾਤ ਨ ਪੁਛੈ ਕੇ ॥ ਕੀਟਾ ਅੰਦਰਿ ਕੀਟੁਕਰਿ ਦੋਸੀ ਦੋਸੁ ਧਰੇ ॥ ਨਾਨਕ ਨਿਰਗੁਣਿ ਗੁਣੁ ਕਰੇ ਗੁਣਵੰਤਿਆ ਗੁਣੁ ਦੇ ॥ ਤੇਹਾ ਕੋਇ ਨਸੁਝਈ ਜਿ ਤਿਸੁ ਗੁਣੁ ਕੋਇ ਕਰੇ ॥੭॥ ਸੁਣਿਐ ਸਿਧ ਪੀਰ ਸੁਰਿ ਨਾਥ ॥ ਸੁਣਿਐ ਧਰਤਿਧਵਲ ਆਕਾਸ ॥ ਸੁਣਿਐ ਦੀਪ ਲੋਅ ਪਾਤਾਲ ॥ ਸੁਣਿਐ ਪੋਹਿ ਨ ਸਕੈ ਕਾਲੁ ॥ ਨਾਨਕਭਗਤਾ ਸਦਾ ਵਿਗਾਸੁ ॥ ਸੁਣਿਐ ਦੂਖ ਪਾਪ ਕਾ ਨਾਸੁ ॥੮॥ ਸੁਣਿਐ ਈਸਰੁ ਬਰਮਾ ਇੰਦੁ॥ ਸੁਣਿਐ ਮੁਖਿ ਸਾਲਾਹਣ ਮੰਦੁ ॥ ਸੁਣਿਐ ਜੋਗ ਜੁਗਤਿ ਤਨਿ ਭੇਦ ॥ ਸੁਣਿਐ ਸਾਸਤਸਿਮ੍ਰਿਤਿ ਵੇਦ ॥";
const ang1e = "ONE UNIVERSAL CREATOR GOD.THE NAME IS TRUTH.CREATIVE BEING PERSONIFIED. NO FEAR. NO HATRED. IMAGE OF THE UNDYING, BEYOND BIRTH, SELF-EXISTENT. BY GURU'S GRACE ~CHANT AND MEDITATE:TRUE IN THE PRIMAL BEGINNING. TRUE THROUGHOUT THE AGES.TRUE HERE AND NOW. O NANAK, FOREVER AND EVER TRUE. || 1 ||By thinking, He cannot be reduced to thought, even by thinking hundreds of thousands of times. By remaining silent, inner silence is not obtained, even by remaining lovingly absorbed deep within. The hunger of the hungry is not appeased, even by piling up loads of worldly goods. Hundreds of thousands of clever tricks, but not even one of them will go along with you in the end. So how can you become truthful? And how can the veil of illusion be torn away? O Nanak, it is written that you shall obey the Hukam of His Command, and walk in the Way of His Will. || 1 || By His Command, bodies are created; His Command cannot be described. By His Command, souls come into being; by His Command, glory and greatness are obtained. By His Command, some are high and some are low; by His Written Command, pain and pleasure are obtained. Some, by His Command, are blessed and forgiven; others, by His Command, wander aimlessly forever. Everyone is subject to His Command; no one is beyond His Command. O Nanak, one who understands His Command, does not speak in ego. || 2 || Some sing of His Power-who has that Power? Some sing of His Gifts, and know His Sign and Insignia. Some sing of His Glorious Virtues, Greatness and Beauty. Some sing of knowledge obtained of Him, through difficult philosophical studies. Some sing that He fashions the body, and then again reduces it to dust. Some sing that He takes life away, and then again restores it.";
const ang2e = "Some sing that He seems so very far away. Some sing that He watches over us, face to face, ever-present. There is no shortage of those who preach and teach. Millions upon millions offer millions of sermons and stories. The Great Giver keeps on giving, while those who receive grow weary of receiving. Throughout the ages, consumers consume. The Commander, by His Command, leads us to walk on the Path. O Nanak, He blossoms forth, Carefree and Untroubled. || 3 || True is the Master, True is His Name-speak it with infinite love. People beg and pray, 'Give to us, give to us', and the Great Giver gives His Gifts. So what offering can we place before Him, by which we might see the Darbaar of His Court? What words can we speak to evoke His Love? In the Amrit Vaylaa, the ambrosial hours before dawn, chant the True Name, and contemplate His Glorious Greatness. By the karma of past actions, the robe of this physical body is obtained. By His Grace, the Gate of Liberation is found. O Nanak, know this well: the True One Himself is All. || 4 || He cannot be established, He cannot be created. He Himself is Immaculate and Pure. Those who serve Him are honored. O Nanak, sing of the Lord, the Treasure of Excellence. Sing, and listen, and let your mind be filled with love. Your pain shall be sent far away, and peace shall come to your home. The Guru's Word is the Sound-current of the Naad; the Guru's Word is the Wisdom of the Vedas; the Guru's Word is all-pervading. The Guru is Shiva, the Guru is Vishnu and Brahma; the Guru is Paarvati and Lakhshmi. Even knowing God, I cannot describe Him; He cannot be described in words. The Guru has given me this one understanding: there is only the One, the Giver of all souls. May I never forget Him! ||";
const angE = "5 || If I am pleasing to Him, then that is my pilgrimage and cleansing bath. Without pleasing Him, what good are ritual cleansings? I gaze upon all the created beings: without the karma of good actions, what are they given to receive? Within the mind are gems, jewels and rubies, if you listen to the Guru's Teachings, even once. The Guru has given me this one understanding: there is only the One, the Giver of all souls. May I never forget Him! || 6 || Even if you could live throughout the four ages, or even ten times more, and even if you were known throughout the nine continents and followed by all, with a good name and reputation, with praise and fame throughout the world- still, if the Lord does not bless you with His Glance of Grace, then who cares? What isthe use? Among worms, you would be considered a lowly worm, and even contemptiblesinners would hold you in contempt. O Nanak, God blesses the unworthy with virtue,and bestows virtue on the virtuous. No one can even imagine anyone who can bestowvirtue upon Him. || 7 || Listening the Siddhas, the spiritual teachers, the heroicwarriors, the yogic masters. Listening the earth, its support and the Akaashic ethers.Listening the oceans, the lands of the world and the nether regions of the underworld.Listening-Death cannot even touch you. O Nanak, the devotees are forever in bliss.Listening-pain and sin are erased. || 8 || Listening-Shiva, Brahma and Indra.Listening even foul-mouthed people praise Him. Listening the technology of Yogaand the secrets of the body. Listening the Shaastras, the Simritees and the Vedas. ONanak, the devotees are forever in bliss.";

const page = document.getElementById('label');

const pagee = document.getElementById('labele');
let init = Math.round(Math.random() * 3) + 1;


if (init === 1){
    page.innerHTML = ang1;
    pagee.innerHTML = ang1e;
}else if (init === 2){
    page.innerHTML = ang2;
    pagee.innerHTML = ang2e; 
}else if(init === 3){
    page.innerHTML = ang;
    pagee.innerHTML = angE;
}
console.log(init)